package com.openlattice.chronicle.util

import com.openlattice.chronicle.storage.ChroniclePostgresTables
import com.openlattice.chronicle.storage.PostgresEventTables

/**
 * Utility class for validating SQL identifiers to prevent SQL injection attacks.
 *
 * This class provides allowlist-based validation for dynamic table and column names
 * that cannot be parameterized in prepared statements. All dynamic identifiers MUST
 * be validated through this class before being used in SQL statements.
 *
 * @author uzaira0
 */
public object SqlIdentifierValidator {

    /**
     * Maximum length for any SQL identifier (PostgreSQL limit is 63 characters)
     */
    private const val MAX_IDENTIFIER_LENGTH = 63

    /**
     * Regex pattern for valid SQL identifiers.
     * Allows alphanumeric characters, underscores, and must start with a letter or underscore.
     */
    private val VALID_IDENTIFIER_PATTERN = Regex("^[a-zA-Z_][a-zA-Z0-9_]*$")

    /**
     * Regex pattern for temp table names generated by RandomStringUtils.
     * Format: prefix_alphanumeric (e.g., "duplicate_events_ABC123xyz")
     */
    private val TEMP_TABLE_PATTERN = Regex("^[a-z_]+[a-zA-Z0-9_]*$")

    /**
     * Allowed temp table prefixes - these are the only prefixes that can be used
     * for dynamically generated temporary table names.
     */
    private val ALLOWED_TEMP_TABLE_PREFIXES = setOf(
        "duplicate_events_",
        "duplicate_ios_events_",
        "temp_",
        "tmp_"
    )

    /**
     * Allowlist of known table names from ChroniclePostgresTables and PostgresEventTables.
     * This set is populated from the actual table definitions to ensure consistency.
     */
    private val ALLOWED_TABLE_NAMES: Set<String> by lazy {
        buildSet {
            // Add all Chronicle PostgreSQL tables
            add(ChroniclePostgresTables.STUDIES.name)
            add(ChroniclePostgresTables.CANDIDATES.name)
            add(ChroniclePostgresTables.STUDY_PARTICIPANTS.name)
            add(ChroniclePostgresTables.PARTICIPANT_STATS.name)
            add(ChroniclePostgresTables.LEGACY_STUDY_IDS.name)
            add(ChroniclePostgresTables.ORGANIZATIONS.name)
            add(ChroniclePostgresTables.APP_USAGE_SURVEY.name)
            add(ChroniclePostgresTables.QUESTIONNAIRES.name)
            add(ChroniclePostgresTables.FILTERED_APPS.name)
            add(ChroniclePostgresTables.SYSTEM_APPS.name)
            add(ChroniclePostgresTables.TIME_USE_DIARY_SUBMISSIONS.name)
            add(ChroniclePostgresTables.TIME_USE_DIARY_SUMMARIZED.name)
            add(ChroniclePostgresTables.NOTIFICATIONS.name)
            add(ChroniclePostgresTables.AUDIT_BUFFER.name)
            add(ChroniclePostgresTables.PERMISSIONS.name)
            add(ChroniclePostgresTables.PRINCIPALS.name)
            add(ChroniclePostgresTables.DEVICES.name)
            add(ChroniclePostgresTables.ANDROID_SENSOR_DATA.name)
            add(ChroniclePostgresTables.QUESTIONNAIRE_SUBMISSIONS.name)
            add(ChroniclePostgresTables.UPLOAD_BUFFER.name)

            // Add Postgres event storage tables
            add(PostgresEventTables.CHRONICLE_USAGE_EVENTS.name)
            add(PostgresEventTables.CHRONICLE_USAGE_STATS.name)
            add(PostgresEventTables.IOS_SENSOR_DATA.name)
            add(PostgresEventTables.PREPROCESSED_USAGE_EVENTS.name)
        }
    }

    /**
     * Exception thrown when SQL identifier validation fails.
     */
    public class InvalidSqlIdentifierException(
        message: String,
        public val identifier: String,
        public val validationType: ValidationType
    ) : SecurityException(message)

    /**
     * Types of validation that can be performed.
     */
    public enum class ValidationType {
        TABLE_NAME,
        COLUMN_NAME,
        TEMP_TABLE_NAME,
        IDENTIFIER
    }

    /**
     * Validates that a table name is in the allowlist of known tables.
     *
     * @param tableName The table name to validate
     * @return The validated table name (unchanged if valid)
     * @throws InvalidSqlIdentifierException if the table name is not in the allowlist
     */
    @JvmStatic
    public fun validateTableName(tableName: String): String {
        if (tableName.isBlank()) {
            throw InvalidSqlIdentifierException(
                "Table name cannot be blank",
                tableName,
                ValidationType.TABLE_NAME
            )
        }

        if (tableName !in ALLOWED_TABLE_NAMES) {
            throw InvalidSqlIdentifierException(
                "Table name '$tableName' is not in the allowlist of known tables. " +
                    "Add it to SqlIdentifierValidator.ALLOWED_TABLE_NAMES if it's a legitimate table.",
                tableName,
                ValidationType.TABLE_NAME
            )
        }

        return tableName
    }

    /**
     * Validates a temporary table name that was generated dynamically.
     * Temp table names must:
     * 1. Start with an allowed prefix
     * 2. Contain only alphanumeric characters and underscores after the prefix
     * 3. Not exceed maximum identifier length
     *
     * @param tempTableName The temporary table name to validate
     * @return The validated temp table name (unchanged if valid)
     * @throws InvalidSqlIdentifierException if the temp table name is invalid
     */
    // reason: security validator — each throw is a distinct rejection reason/message; merging would lose injection-audit detail
    @Suppress("ThrowsCount")
    @JvmStatic
    public fun validateTempTableName(tempTableName: String): String {
        if (tempTableName.isBlank()) {
            throw InvalidSqlIdentifierException(
                "Temporary table name cannot be blank",
                tempTableName,
                ValidationType.TEMP_TABLE_NAME
            )
        }

        if (tempTableName.length > MAX_IDENTIFIER_LENGTH) {
            throw InvalidSqlIdentifierException(
                "Temporary table name exceeds maximum length of $MAX_IDENTIFIER_LENGTH characters",
                tempTableName,
                ValidationType.TEMP_TABLE_NAME
            )
        }

        val hasValidPrefix = ALLOWED_TEMP_TABLE_PREFIXES.any { prefix ->
            tempTableName.startsWith(prefix)
        }

        if (!hasValidPrefix) {
            throw InvalidSqlIdentifierException(
                "Temporary table name '$tempTableName' does not start with an allowed prefix. " +
                    "Allowed prefixes: $ALLOWED_TEMP_TABLE_PREFIXES",
                tempTableName,
                ValidationType.TEMP_TABLE_NAME
            )
        }

        if (!TEMP_TABLE_PATTERN.matches(tempTableName)) {
            throw InvalidSqlIdentifierException(
                "Temporary table name '$tempTableName' contains invalid characters. " +
                    "Only alphanumeric characters and underscores are allowed.",
                tempTableName,
                ValidationType.TEMP_TABLE_NAME
            )
        }

        return tempTableName
    }

    /**
     * Validates a generic SQL identifier (table name, column name, etc.).
     * This is a more permissive validation for cases where we cannot use an allowlist.
     *
     * @param identifier The identifier to validate
     * @return The validated identifier (unchanged if valid)
     * @throws InvalidSqlIdentifierException if the identifier is invalid
     */
    // reason: security validator — each throw is a distinct rejection reason/message; merging would lose injection-audit detail
    @Suppress("ThrowsCount")
    @JvmStatic
    public fun validateIdentifier(identifier: String): String {
        if (identifier.isBlank()) {
            throw InvalidSqlIdentifierException(
                "SQL identifier cannot be blank",
                identifier,
                ValidationType.IDENTIFIER
            )
        }

        if (identifier.length > MAX_IDENTIFIER_LENGTH) {
            throw InvalidSqlIdentifierException(
                "SQL identifier exceeds maximum length of $MAX_IDENTIFIER_LENGTH characters",
                identifier,
                ValidationType.IDENTIFIER
            )
        }

        if (!VALID_IDENTIFIER_PATTERN.matches(identifier)) {
            throw InvalidSqlIdentifierException(
                "SQL identifier '$identifier' contains invalid characters. " +
                    "Identifiers must start with a letter or underscore, " +
                    "and contain only alphanumeric characters and underscores.",
                identifier,
                ValidationType.IDENTIFIER
            )
        }

        // Check for SQL keywords that could be used in injection attacks
        if (isSqlKeyword(identifier.uppercase())) {
            throw InvalidSqlIdentifierException(
                "SQL identifier '$identifier' is a reserved SQL keyword",
                identifier,
                ValidationType.IDENTIFIER
            )
        }

        return identifier
    }

    /**
     * Validates an identifier for use in import operations where table names
     * come from external configuration. These must match the validation pattern
     * used in ImportStudiesConfiguration.
     *
     * @param identifier The identifier to validate
     * @return The validated identifier (unchanged if valid)
     * @throws InvalidSqlIdentifierException if the identifier is invalid
     */
    // reason: security validator — each throw is a distinct rejection reason/message; merging would lose injection-audit detail
    @Suppress("ThrowsCount")
    @JvmStatic
    public fun validateImportTableName(identifier: String): String {
        if (identifier.isBlank()) {
            throw InvalidSqlIdentifierException(
                "Import table name cannot be blank",
                identifier,
                ValidationType.TABLE_NAME
            )
        }

        if (identifier.length > 255) {
            throw InvalidSqlIdentifierException(
                "Import table name exceeds maximum length of 255 characters",
                identifier,
                ValidationType.TABLE_NAME
            )
        }

        // Import sources may be schema-qualified (e.g. "src.system_apps", per
        // ImportStudiesConfiguration). The value is interpolated into raw SQL (it cannot be
        // parameterized), so validate each dot-separated segment as a strict SQL identifier:
        // this rejects injection metacharacters, hyphens, leading digits, empty segments, and
        // more than one qualifier — and rejects the system catalogs (information_schema / pg_*)
        // that a qualified name could otherwise reach (e.g. "information_schema.columns").
        val segments = identifier.split('.')
        if (segments.size > 2) {
            throw InvalidSqlIdentifierException(
                "Import table name '$identifier' has too many qualifiers; expected 'table' or 'schema.table'.",
                identifier,
                ValidationType.TABLE_NAME
            )
        }
        segments.forEach { segment ->
            if (!VALID_IDENTIFIER_PATTERN.matches(segment)) {
                throw InvalidSqlIdentifierException(
                    "Import table name '$identifier' contains an invalid identifier segment '$segment'. " +
                        "Each segment must start with a letter or underscore and contain only letters, digits, and underscores.",
                    identifier,
                    ValidationType.TABLE_NAME
                )
            }
            val lowerSegment = segment.lowercase()
            if (lowerSegment.startsWith("pg_") || lowerSegment == "information_schema") {
                throw InvalidSqlIdentifierException(
                    "Import table name '$identifier' references reserved system catalog '$segment'.",
                    identifier,
                    ValidationType.TABLE_NAME
                )
            }
        }

        return identifier
    }

    /**
     * Checks if a string is a reserved SQL keyword.
     */
    private fun isSqlKeyword(identifier: String): Boolean {
        return identifier in SQL_RESERVED_KEYWORDS
    }

    /**
     * Set of reserved SQL keywords that should not be used as identifiers.
     */
    private val SQL_RESERVED_KEYWORDS = setOf(
        "SELECT", "INSERT", "UPDATE", "DELETE", "DROP", "CREATE", "ALTER",
        "TABLE", "DATABASE", "INDEX", "VIEW", "TRIGGER", "PROCEDURE", "FUNCTION",
        "FROM", "WHERE", "AND", "OR", "NOT", "IN", "BETWEEN", "LIKE", "IS", "NULL",
        "TRUE", "FALSE", "AS", "ON", "JOIN", "LEFT", "RIGHT", "INNER", "OUTER",
        "CROSS", "NATURAL", "USING", "GROUP", "BY", "HAVING", "ORDER", "ASC", "DESC",
        "LIMIT", "OFFSET", "UNION", "INTERSECT", "EXCEPT", "ALL", "DISTINCT",
        "INTO", "VALUES", "SET", "DEFAULT", "CONSTRAINT", "PRIMARY", "KEY",
        "FOREIGN", "REFERENCES", "CHECK", "UNIQUE", "CASCADE", "RESTRICT",
        "GRANT", "REVOKE", "EXECUTE", "TRUNCATE", "COMMIT", "ROLLBACK", "BEGIN",
        "END", "TRANSACTION", "SAVEPOINT", "CASE", "WHEN", "THEN", "ELSE", "IF",
        "WHILE", "FOR", "LOOP", "RETURN", "DECLARE", "CURSOR", "FETCH", "CLOSE",
        "OPEN", "WITH", "RECURSIVE", "TEMPORARY", "TEMP", "UNLOGGED", "SCHEMA",
        "OWNER", "AUTHORIZATION", "SESSION", "LOCAL", "GLOBAL", "CURRENT",
        "ROW", "ROWS", "FIRST", "LAST", "NEXT", "PRIOR", "ABSOLUTE", "RELATIVE",
        "ADMIN", "USER", "ROLE", "PASSWORD", "LOGIN", "CONNECTION", "ENCODING",
        "COPY", "BINARY", "DELIMITER", "QUOTE", "ESCAPE", "HEADER", "FORMAT",
        "FORCE", "FREEZE", "VERBOSE", "ANALYZE", "VACUUM", "REINDEX", "CLUSTER"
    )

    /**
     * Creates a quoted identifier for PostgreSQL.
     * This can be used for identifiers that need to be quoted but should still be validated first.
     *
     * @param identifier The identifier to quote
     * @return The quoted identifier
     * @throws InvalidSqlIdentifierException if the identifier is invalid
     */
    @JvmStatic
    public fun quoteIdentifier(identifier: String): String {
        validateIdentifier(identifier)
        // Double any embedded quotes to prevent injection
        val escaped = identifier.replace("\"", "\"\"")
        return "\"$escaped\""
    }

    /**
     * Validates that a numeric timeout value is within acceptable bounds.
     *
     * @param timeoutMillis The timeout value in milliseconds
     * @return The validated timeout value
     * @throws IllegalArgumentException if the timeout is invalid
     */
    @JvmStatic
    public fun validateTimeout(timeoutMillis: Long): Long {
        require(timeoutMillis >= 0) { "Timeout cannot be negative: $timeoutMillis" }
        require(timeoutMillis <= 3600000) { "Timeout exceeds maximum of 1 hour: $timeoutMillis" }
        return timeoutMillis
    }
}
